### ISSUE TITLE
List and filter seniors based on technologies, available time

### ISSUE THREAD

**Issue by Mert18** [sosyal-app/backend#98]

**Comment by yekxp** [comment]
Hi, again Jake :D . Can i take this issue, too? It seems so interesting and I like to work with database :).

**Comment by Mert18** [comment]
Hi again, however you want :) Let me remind that we did not think much about the format of "available time" yet, you can finish the task as long as you do listing and filtering. And if filtering seems hard, open pr without it, we then open another issue for filtering.

Criteria queries may help with the filtering, but if you have any other methods, we are open :) Good luck.

**Comment by yekxp** [comment]
Hi, I just want to announce that I am working on the task and it will be ready by the end of the week.

**Comment by Mert18** [comment]
No problem, but since we are still at the beginning of development, there may be global changes throughout the codebase. So do not forget to pull the latest changes to your branch before opening your pull request. Otherwise there may be merge conflicts.

I have added a new variable to Technology class yesterday. I hope this would not interrupt your work.

**Comment by yekxp** [comment]
Yes, i need change Period Time, to better handling. But I'm finalizing it successfully, only minor mistakes in the entries.  hope you don't mind that it took a bit longer, but I had other obligations, also I will present this task in school as part of a project and I have to do it at certain intervals

**Comment by Mert18** [comment]
I do not mind at all. I appreciate your work. Take your time.

**Comment by Mert18** [comment]
#141 closes
